Feature/ef 169 caliper update 1 1
hmhco/caliper-common-fixtures pull request #23
Opened 2019-06-05 14:36 UTC by neil-buckley

Draft of 2 (of 3) events originating for RCE

2019-06-05 14:54 UTC, odowdj requested changes

2019-06-05 14:54 UTC, odowdj commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
no need for userRole here - its already in Membership as Learner

2019-06-05 14:54 UTC, odowdj commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "index": 1
I dont think `index` is a valid field?

2019-06-05 14:54 UTC, odowdj commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "event": {
I don't think `event` is a valid field - see here https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html#navigationEvent for valid fields for this NavigationEvent

2019-06-05 14:57 UTC, neil-buckley commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "event": {
👍

2019-06-05 14:58 UTC, neil-buckley commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "index": 1
👍

2019-06-06 16:46 UTC, raphaelsantos commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
Hi @odowdj, this `userRole` property is currently being used by the Content Tree Service, so I believe we should keep it at least for the moment.

cc @harleys-hmh

2019-06-06 16:50 UTC, harleys-hmh commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
cc @drochgenius @chrisunl

2019-06-06 16:57 UTC, kevinmcgarry submitted a review, later dismissed

2019-06-06 16:57 UTC, kevinmcgarry commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "dateCreated": "2019-06-05T14:17:34.739Z",
I would drop `dateCreated` as it is the date created of the content object which we don't care about and it is optional.

2019-06-06 16:57 UTC, kevinmcgarry commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "eventTime": 1559744254740,
This eventTime should be ISO8601 format. The spec says `An ISO 8601 date and time value expressed with millisecond precision that indicates when the Event occurred. The value MUST be expressed using the format YYYY-MM-DDTHH:mm:ss.SSSZ set to UTC with no offset specified.`

2019-06-06 16:57 UTC, kevinmcgarry commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "id": "http://rce.localhost/RCE",
Some other apps are using the string format of `edApp` instead of json object format you have here. see example here: https://github.com/hmhco/caliper-common-fixtures/blob/master/src/test/resources/fixtures/hmh/hmh-ri/released/caliperEventAssessmentStarted.json#L20. The problem with using string is that you can't add extensions or any other json attribute, so if you need extensions (as you have done here) then you should go as-is with the json object instead of the string format. Howevever if you interpreted `offline` as an attribute of the navigation event as opposed to an attribute of the `edApp` then you could proceed with `edApp` as a single string like `"edApp": "https://www.hmhco.com/RCE"`.

2019-06-06 16:57 UTC, kevinmcgarry commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "subOrganizationOf": {
Once we have a link to the parent section or school then in theory we don't need the parent of the parent so you could drop this `subOrganization` data as we can get it later from other sources. The only reason to keep it would be if you want to do some realtime processing and it might be more convenient to have it in the message. However overall I'd prefer to reduce the verbosity of the message by removing it. I can't remember from spec - is there a way to know if the `organization` in the spec is a `section` or a `school`?

2019-06-07 09:54 UTC, neil-buckley commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "subOrganizationOf": {
Cool, will remove suborg - there's no type of org in the spec, I guess we could chuck it in the name or description - is it necessary?

2019-06-07 09:56 UTC, neil-buckley commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "id": "http://rce.localhost/RCE",
Bit of context :) The RCE has two modes standalone hosted on Ed, or within HMH player hosted on Ed, or offline in the HMHPPlayer. the EdApp changes depending on this context. IF in the HMHPlayer rather than RCE the edApp is HMHPlayer

2019-06-07 09:56 UTC, neil-buckley commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "eventTime": 1559744254740,
Cool

2019-06-07 09:56 UTC, neil-buckley commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "dateCreated": "2019-06-05T14:17:34.739Z",
Cool

2019-06-07 11:59 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
I would guess that the extension properties beginning with content could all be addressed by using standard properties and the isPartOf mechanism, but I'd need details on what the intent of these extensions is to be more specific.
And I also so no purpose of userRole here.

2019-06-07 12:06 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "index": 1
I can't again say without context, but if the intent of index is to show the position of this resource in the parent resource it may be addressed by having the isPartOf be a DigitalResourceCollection and which has an items array of the uris of all of it's children, including this DigitalResource.

2019-06-07 12:07 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "event": {
What is here in event seems to duplicate what is added under object also, so presumably it can just be deleted.

2019-06-07 12:14 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "event": {
On the edApp I wonder if we need an explicit offline property, I would presume that is could be inferred from a difference in the sensor sendTime (now) and the eventTime (potentially ages ago). Also for time properties the value MUST be expressed using the format YYYY-MM-DDTHH:mm:ss.SSSZ set to UTC with no offset specified.

2019-06-07 12:29 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +    "index": 1
dateCreated is Optional, so we can leave it out if it is not valuable. Putting it in only when there is value helps to draw attention to that value (e.g. if it is a newly created resource that might be important information).

Also below, if we don't need the referrer type or name then in Caliper (don't know about the pipeline) you'd only need to have:
"referrer": "http://rce.localhost/content/book/OPS/page0001.xhtml",
"edApp": "http://rce.localhost/RCE",

2019-06-07 12:34 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "event": {
As a general change we should move to the same model for group and membership as now used in the GradedEvent (for 1.1)

2019-06-07 12:35 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +  "event": {
On both of these events the session object is missing

2019-06-07 13:07 UTC, neil-buckley commented
thanks @padraig-ohiceadha @odowdj @kevinmcgarry I think I've addressed all the changes now

2019-06-07 14:03 UTC, harleys-hmh commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
Hi @padraig-ohiceadha - per Raphael's comment above, this is being used to differentiate between different TOCs on the analytics side.

2019-06-07 15:20 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
Is the Content Tree Service using a Caliper 1.1 event (rather than a 1.0 event)?
How could they be using it in a Caliper 1.1 event if this is marked as an addition to our current 1.1 format?
I don't see why the Content Tree Service can't fix their code to use the correct property before migrating to use Caliper 1.1.
So I would recommend that we do not add userRole to the 1.1 event.
Out of interest what use do they make of it?

2019-06-07 15:26 UTC, padraig-ohiceadha commented
> thanks @padraig-ohiceadha @odowdj @kevinmcgarry I think I've addressed all the changes now

Hi @neil-buckley 
    There is still no information on the purpose of the extensions to the DigitalResource. There is nothing to show that we need extensions here (if we can address the business need with standard properties then adding extensions is incorrect), however I can't suggest the correct properties to add without knowing what these extension properties are supposed to mean and what use they are being put to.

    All the best,

        Padraig

2019-06-07 15:45 UTC, neil-buckley commented
@harleys-hmh / @drochgenius / @raphaelsantos would you mind liaising with @padraig-ohiceadha on what the purpose is of the data in the object extension, I'm off for next two week, but happy to amend based on what ever you guys end up with.

2019-06-07 15:46 UTC, harleys-hmh commented
Sure thing @neil-buckley !

2019-06-07 16:08 UTC, harleys-hmh commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
Hi @padraig-ohiceadha - I'll set something up to chat about this early next week, so you get context on what we're doing re: Content Tree Service, and the business need.

2019-06-07 16:10 UTC, padraig-ohiceadha commented on src/test/resources/fixtures/hmh/hmh-rce/development/caliperEventNavigationEvent.json
> +      "userRole": "student",
@harleys-hmh Great, Thanks

2019-06-10 08:59 UTC, kevinmcgarry commented
@harleys-hmh please invite me (Kevin McGarry) and @odowdj too, thanks

2019-07-11 12:45 UTC, neil-buckley commented
@harleys-hmh @padraig-ohiceadha any movement/agreement on how this should proceed?

2019-07-11 13:46 UTC, harleys-hmh commented
Hi @neil-buckley - I have a note to follow up with @padraig-ohiceadha and yourself by email, but in the short term, the Analytics team needs a mechanism to match Caliper event data against HMH's internal metadata stores (i.e. Content Tree Service), which the extension data allow.

I am all for planning to better use `isPartOf` in the mid-term, but do not think this should preclude updating to Caliper 1.1. As it is, RCE has been emitting Caliper 1.0 events with these extension data for the majority of 2019, so there is already a large dataset for the Analytics team to analyze using these. I would suggest that we maintain that format until they provide concrete feedback on how we can better improve our analytics data.

As a reminder, our objective here is to provide HMH with user insights, and the current approach has been validated by multiple teams and stakeholders as a means to support this.

Thanks,
Scott

2019-07-11 13:50 UTC, neil-buckley commented
thanks @harleys-hmh 

@odowdj & @kevinmcgarry does this PR look like it meets the needs of all parties now? Cheers!

2019-07-22 12:28 UTC, neil-buckley commented
Hi guys, how we looking at proceeding with the PR? @odowdj @kevinmcgarry

2019-08-09 13:51 UTC, neil-buckley commented
@kevinmcgarry @odowdj - messages updated - they represent changes discussed with more representative book data (now social studies.

2019-08-19 12:13 UTC, neil-buckley commented
Updated with observations from call, image attached shows the hierarchy of the book reflected in the isPartOf sequence 
![Screenshot 2019-08-19 at 12 21 21](https://user-images.githubusercontent.com/3385748/63264506-25ab5300-c283-11e9-927c-bcf6e883c6fc.png)

2019-08-19 13:59 UTC, odowdj approved these changes

2019-08-19 16:21 UTC, merged